class SemanticCube:
	def __init__(self):
		self.cube = {'int' : {'int' : {'+': 'int',
                                            '-': 'int',
                                            '/': 'float',
                                            '*': 'int',
                                            '%': 'int',
                                            '<': 'boolean',
                                            '>': 'boolean',
                                            '<=': 'boolean',
                                            '>=': 'boolean',
                                            '!=': 'boolean',
                                            '==': 'boolean',
                                            '=': 'int'},
                                  'float': {'+': 'float',
                                            '-': 'float',
                                            '/': 'float',
                                            '*': 'float',
                                            '%': 'float',
                                            '<': 'boolean',
                                            '>': 'boolean',
                                            '<=': 'boolean',
                                            '>=': 'boolean',
                                            '!=': 'boolean',
                                            '==': 'boolean',
                                            '=': 'int'}},
                         'float' : {'int' : {'+': 'float',
                                            '-': 'float',
                                            '/': 'float',
                                            '*': 'float',
                                            '%': 'float',
                                            '<': 'boolean',
                                            '>': 'boolean',
                                            '<=': 'boolean',
                                            '>=': 'boolean',
                                            '!=': 'boolean',
                                            '==': 'boolean',
                                             '=': 'float'},
                                  'float': {'+': 'float',
                                            '-': 'float',
                                            '/': 'float',
                                            '*': 'float',
                                            '%': 'float',
                                            '<': 'boolean',
                                            '>': 'boolean',
                                            '<=': 'boolean',
                                            '>=': 'boolean',
                                            '!=': 'boolean',
                                            '==': 'boolean',
                                            '=': 'float'}},
                         'boolean' : {'boolean' : {'&&' : 'boolean',
                                             '||' : 'boolean',
                                             '=' : 'boolean'}}}